#!/bin/bash

#	Tag head of master branch with timestamp
#	Create file called taglog
#		Output all of the tags in the repo
#		Sort reverse alphabetical order
#		Insert new tag at the end of the file
#		
#	Take this script and put in a Jenkins job
#	Run the job
#	You should be able to send in a var


#Variables

        TIMESTAMP=$(date +'%m/%d/%Y') #Define TIMESTAMP
	TAGNAME=$USER-$TIMESTAMP

#Executables
	

	git tag $TAGNAME     #tag the HEAD

	git tag | sort -r > taglog      #List tags in reverse alphabetical order in file: taglog
	
	echo "$TAGNAME" >> taglog     #Put a copy of the tag at end of the file: taglog

#	sed '$ TAGNAME' taglog
#	sed -i '' -e '$TAGNAME\' taglog#

	git add .
	
	git commit

	git push --tags     #push tags to remote repo

	git push origin master     #push local changes to remote repo

        echo -e "\nYou have recorded a tag named: $TAGNAME\n\n" #confirm the tag



